version: '3.9'
services:
  dailyjournaling.api:
    image: ${DOCKER_REGISTRY-}dailyjournalingapi
    container_name: dailyjournaling-api
    build:
      context: .
      dockerfile: DailyJournaling.API/Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Redis__ConnectionString=cache:${REDIS_PORT}
    depends_on:
      - db
      - cache
    networks:
      - app-network

  db:
    image: postgres:16.4
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis:7.4.0
    container_name: redis-cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
